### ISSUE TITLE
Récupérer une route nommé

### ISSUE THREAD

**Issue by TuxBoy** [stratifyphp/twig-module#1]
Hi,

I try to recover a route by its name that I defined:

```php
...
route(function () {}, 'name')
...
```
But I have this error when I use in the view `path('home')` : "No route named "home" was found". there is a different configuration to be made than that defined in the documentation ?

Thanks.

**Comment by mnapoli** [comment]
Hey there, sorry for the delay. I *think* named route doesn't work for now unfortunately (this package is mostly beta stuff :/ )

**Comment by TuxBoy** [comment]
Thank you for your reply. :)
